### ISSUE TITLE
Consider bridge to stanfordNLP

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/python-gatenlp#14]
See https://stanfordnlp.github.io/stanfordnlp/ and https://github.com/stanfordnlp/stanfordnlp

This is probably more complex than spacy since it uses conll format internally and discards space. 

Also interesting: this distinguishes between tokens and words!

**Comment by greenwoodma** [comment]
Given that StanfordNLP appears, at least in part, to be a python wrapper around CoreNLP it seems silly for us to provide a python bridge to it, when for performance/stability reasons it would be much better to juts use CoreNLP directly from within GATE.
Mind you this whole gate/python thing keeps confusing me so have I missed something obvious?

**Comment by johann-petrak** [comment]
1) StanfordNLP 2.0 is both a Python implementation based on Pytorch neural network models and a wrapper for CoreNLP
2) gatenlp can be used independently from Java GATE so it makes sense to let it have its own bridges and wrappers
3) StanfordNLP is Apache licensed, CoreNLP is GPL (not LGPL) licensed

However, as the original issue text says, their abstractions do not deal with space, so it may be too much hassle to do this -- the issue is mainly here to remind me we *could* do it, but low priority.

**Comment by johann-petrak** [comment]
Initial module implemented.
