### ISSUE TITLE
Format gatexml reader: handle XML encodings

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/python-gatenlp#176]
We currently assume the XML file is utf-8 encoded but most older GATE XML files are not and have a header like

```
<?xml version="1.0" encoding="windows-1252" ?>
```

Figure out the proper way to read such an xml file and get the encoding right

**Comment by johann-petrak** [comment]
OK, this is weird: the document that has the windows-1252 encoding in the header seems to be in UTF8 actually? This is e.g. file "ft-BT-briefing-02-aug-2001.xml" from the JAPE module of the GATE course. `file JAPE/corpus/ft-BT-briefing-02-aug-2001.xml` reports this file to be UTF-8 and the pound character in there is show correctly on my UTF8 console. 

Loading this XML into gatenlp shows a weird character which seems to be right though: if I change the header in the file to "utf8" the pound symbol is shown correctly after loading.

So it seems this is not a bug in gatenlp but in the XML document that is used for the handouts in the GATE course.

**Comment by johann-petrak** [comment]
OK, so it turns out that this is probably just a problem with the document itself.
Normally, if people have saved a GATE XML document with some non-UTF8 encoding, that encoding should actually get stored in the header. 
Which means that what we do should already be the right thing.

**Comment by ianroberts** [comment]
For ref:

https://github.com/GateNLP/gate-core/blob/21681fb9135cd8c2921c83b591e78846c9cfef5b/src/main/java/gate/corpora/DocumentStaxUtils.java#L956-L979
