### ISSUE TITLE
Auto-detection or auto-install of GATE?

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/python-gatenlp#37]
Maybe support using the gate worker without explicitly pointing to an existing gate installation somehow: 

* Try to find GATE, but this is very hard if it is not on the path
* do some on-the-fly installation of gate ourselves into a standard gatenlp config location (HOME/.gatenlp or HOME/.config/gatenlp on Linux, similar on Windows).

**Comment by ianroberts** [comment]
* use a small bootstrapping JAR file like the Maven Wrapper to download the requirements from Central at runtime (assuming we're only working here with 8.6.1 and Maven-style plugins)

**Comment by johann-petrak** [comment]
>     * use a small bootstrapping JAR file like the Maven Wrapper to download the requirements from Central at runtime (assuming we're only working here with 8.6.1 and Maven-style plugins)

Thanks, that looks cool!

**Comment by greenwoodma** [comment]
or given you are in python already what about using a python package to do the maven artifact download, would save the need to grab the bootstrapping jar and might be easier to handle errors etc. This was the first one that cropped up when I did a quick google https://pypi.org/project/maven-artifact-downloader/

**Comment by johann-petrak** [comment]
> or given you are in python already what about using a python package to do the maven artifact download, would save the need to grab the bootstrapping jar and might be easier to handle errors etc. This was the first one that cropped up when I did a quick google https://pypi.org/project/maven-artifact-downloader/

Thanks, this looks interesting as well, did not even consider that python would be able to do this! The one you linked is GPL 3 though, so not sure if I want to use it. 

I already got the approach using the Maven wrapper to work and it can also generate the gate.classpath file, using the maven dependency plugin, so I think that should be fine. 

I will have to look of the details (as the maven command would have to run in a writable directory and put the gate.classpath file there, not the one where it comes with the python package), but otherwise it looks good. 

This is low priority anyways, using the GATE Slave from Python is probably not for the average user :)

**Comment by johann-petrak** [comment]
It may actually be easier to just tell people to copy-paste the path from the GATE icon properties. Maybe make gatenlp to also accept the full exe path and figure gatehome out from that.

**Comment by johann-petrak** [comment]
mvnw.cmd requires JAVA_HOME to be set which is annoying. It expects a JDK to be installed because normally one would want to use Maven to compile Java, but we do not even need that. So changed the script to also work without JAVA_HOME if java.exe is on the path. 

After this, the script runs fine, downloads everything and creates the gate.classpath file.

**Comment by johann-petrak** [comment]
This is all too clumsy and too brittle to do well in a portable way. 

I am now thinking the easiest way to achieve this may be to provide support for doing this:
* download the GATE developer release in zip format and expand in a standard location 
* optionally/if required download a supported java RE zip and expand in a standard location
* use those by default, unless gatehome / java path is provided explicitly
This would have the advantage that it gives gatenlp more control over which versions of GATE and Java are used by default, only requires a single file download and no additional dependencies or separate installation steps.

**Comment by johann-petrak** [comment]
Also change thins so that gate and java are treated identically: instead of the java path, provide java home either as a parameter or through the environment. 

Add parameters:
* `own_gate` : One of "ifneeded" (default), "force", "no"/None
* `own_java`: One of "ifneeded" (default), "force", "no"/None

**Comment by johann-petrak** [comment]
Detection:
* if we have the gatehome/javahome parameter set, use from there
* otherwise if we have ` GATE_HOME` / `JAVA_HOME`  use from the corresponding bin
* otherwise if gate/java is found of the path, set corresponding HOME and use from there
* otherwise, if not disabled, set `GATE_HOME` or `JAVA_HOME` and use from our own downloaded code

So no fancy guessing of common locations or anything.

**Comment by johann-petrak** [comment]
This is just not worth the hassle on Windows and configuring this on Linux is trivial.
