### ISSUE TITLE
Set Operations on Annotation Sets

### ISSUE THREAD

**Issue by mdorkhah** [GateNLP/python-gatenlp#80]
When writing PAMPAC rules, I found it very helpful if I could do Set Operations like Union, Intersection and Difference  for Annotation Sets to have new built Annotation Set to be used as Annotation Set to Match.
For Example if I want to find One Annotation Type after another Annotation Type without considering any other Annotation Type, I need to match within the Union of that two Annotation Types. 

p2 = Seq(Ann(name="tok", type="Type1"),Ann(name="tok1", type="Type2"))
a2 = AddAnn(name="tok1", anntype="newtype")
r2 = Rule(p2,a2)
anns2match = doc.annset("Set1").within("Type1") **UNION** doc2.annset("Set1").within("Type2")
outset = "newset"
Pampac(r2).run(doc, anns2match, outset=outset)

Please consider that the Annotation Types could be from different Annotation Sets.

**Comment by johann-petrak** [comment]
Do you mean `doc.annset("Set1").with_type("Type1")`? the `within` method requires a span or annotation and retrieves annotations within the offset range of the span or annotation.

If you want to get annotations with several annotation types from one set, you can specify multiple annotation types or a list of annotation types for the `with_type` method.

You should be able to create a new annotation set from different sets by:
* creating a detached set e.g. by getting annotations from the first set for some types only
* changing the detached set to be mutable
* adding additional annotations to that detached set from one or more other sets
Note that added annotations are shallow copies and may have different annotation ids as the originals

Example:
```
tmpset = doc.annset("Set1").with_type("Type1", "Type2")
tmpset.immutable = False
for ann in doc.annset("Set2").with_type("Type3"):
    tmpset.add_ann(ann)
```

The set `tmpset` should then contain annotations with types Type1`and Type2 from Set1 and those with Type3 from Set2

**Comment by mdorkhah** [comment]
> Do you mean `doc.annset("Set1").with_type("Type1")`? the `within` method requires a span or annotation and retrieves annotations within the offset range of the span or annotation.
> 
> If you want to get annotations with several annotation types from one set, you can specify multiple annotation types or a list of annotation types for the `with_type` method.
> 
> You should be able to create a new annotation set from different sets by:
> 
> * creating a detached set e.g. by getting annotations from the first set for some types only
> * changing the detached set to be mutable
> * adding additional annotations to that detached set from one or more other sets
>   Note that added annotations are shallow copies and may have different annotation ids as the originals
> 
> Example:
> 
> ```
> tmpset = doc.annset("Set1").with_type("Type1", "Type2")
> tmpset.immutable = False
> for ann in doc.annset("Set2").with_type("Type3"):
>     tmpset.add_ann(ann)
> ```
> 
> The set `tmpset` should then contain annotations with types Type1`and Type2 from Set1 and those with Type3 from Set2
> 
> Is this what you need?

Sorry, I meant with_type
Thank you, it works in my case. However, I doubt if it could work for Intersection or Difference.

**Comment by johann-petrak** [comment]
I am not sure if there is a single most useful way for how to define equality between annotations from different annotation sets for set operations: just the span, the span and type, the span and type and features? 
Probably depends on the application. 

The best way for checking equality, less-than and hashing for annotations is still not finally decided as it has a lot of subtle consequences and also may impact performance.

**Comment by johann-petrak** [comment]
On gatenlp AnnotationSet instances, the way how annotations get added or removed is already well defined. 
Closing this.
