### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by mdorkhah** [GateNLP/python-gatenlp#81]
p_1 = Seq(Ann(name="tok1", type="type1"),Ann(name="tok2", type="type2"),Ann(name="tok3", type="type2"))
p_2 = Seq(Ann(name="tok4", type="type1"),Ann(name="tok5", type="type2"))
anns2match = tmpset
a_1_1 = AddAnn(name="tok2", anntype="type3")
a_1_2 = AddAnn(name="tok3", anntype="type4")
a_2 = AddAnn(name="tok5", anntype="type3")
r_1 = Rule(p_1,a_1_1,a_1_2)
r_2 = Rule(p_2,a_2)
outset = doc.annset("new")
outset.clear()
Pampac(r_1,r_2).run(doc, anns2match, outset=outset)

I tried to do multiple actions (a_1_1, a_1_2) for a pattern (p_1) and this resulted in the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-224-a4ade15594be> in <module>
     17 outset = doc.annset("new")
     18 outset.clear()
---> 19 Pampac(r_1,r_2).run(doc, anns2match, outset=outset)

~\miniconda3\lib\site-packages\gatenlp\pam\pampac.py in __init__(self, skip, select, *rules)
   2270         self.rules = rules
   2271         self.priorities = [r.priority for r in self.rules]
-> 2272         self.max_priority = max(self.priorities)
   2273         for idx, r in enumerate(rules):
   2274             if r.priority == self.max_priority:

TypeError: '>' not supported between instances of 'int' and 'AddAnn'

**Comment by johann-petrak** [comment]
If you look at the pythondocs (https://gatenlp.github.io/python-gatenlp/pythondoc/gatenlp/) for Rule:
https://gatenlp.github.io/python-gatenlp/pythondoc/gatenlp/pam/pampac.html#gatenlp.pam.pampac.Rule
you can see that the Rule only takes a single action. If you specify another parameter it is used for the priority parameter which causes the error. 

Currently it is not possible to specify several actions, however there will be a wrapper to wrap an arbitrary number of actions in the next release. You can add the class that does this to your own code for now:
```
class Actions:
    def __init__(self, *actions):
        self.actions = actions

    def __call__(self, succ, context=None, location=None):
        for action in self.actions:
            action(succ, context=context, location=location)
```

Then you can create a rule with several actions like this:
```
r_1 = Rule(p_1, Actions(a_1_1,a_1_2))
```

Please let me know if this works for you.

**Comment by mdorkhah** [comment]
> If you look at the pythondocs (https://gatenlp.github.io/python-gatenlp/pythondoc/gatenlp/) for Rule:
> https://gatenlp.github.io/python-gatenlp/pythondoc/gatenlp/pam/pampac.html#gatenlp.pam.pampac.Rule
> you can see that the Rule only takes a single action. If you specify another parameter it is used for the priority parameter which causes the error.
> 
> Currently it is not possible to specify several actions, however there will be a wrapper to wrap an arbitrary number of actions in the next release. You can add the class that does this to your own code for now:
> 
> ```
> class Actions:
>     def __init__(self, *actions):
>         self.actions = actions
> 
>     def __call__(self, succ, context=None, location=None):
>         for action in self.actions:
>             action(succ, context=context, location=location)
> ```
> 
> Then you can create a rule with several actions like this:
> 
> ```
> r_1 = Rule(p_1, Actions(a_1_1,a_1_2))
> ```
> 
> Please let me know if this works for you.

Thank you very much!
It works well. 
I thought I can use multiple actions in Rule because of this line of information, "A rule is created by specifying a pattern to match in the document and one or more actions", in the link below:
https://gatenlp.github.io/python-gatenlp/pampac.html

**Comment by johann-petrak** [comment]
Oh thank you for finding this documentation error!

**Comment by johann-petrak** [comment]
This has been fixed in the development version now, closing
