### ISSUE TITLE
AttributeError: 'Result' object has no attribute 'data'

### ISSUE THREAD

**Issue by mdorkhah** [GateNLP/python-gatenlp#98]
I'm using the following function to get all the results from a N rule function:

def annotate_each(succ, context, location):
    res = succ[0]
    print(res)
    print(res.data)
    for data in res.data:
        if data["name"] == "tok2":
            context.outset.add(data["span"], newtype)

def rule():
    global newtype
    p = Seq(Ann(name="tok1", type="type1"), N(Ann(name="tok2", type="type2"), min=1, max=30))
    newtype = "NewType"
    r = Rule(p,annotate_each)
    anns2match = doc2.annset()
    Pampac(r).run(doc2, anns2match, outset=outset)

But I receive the following error:

Traceback (most recent call last):
  File "Main.py", line 521, in <module>
    rule()
  File "Main.py", line 493, in rule
    Pampac(r).run(doc2, anns2match, outset=outset)
  File "C:\ProgramData\Anaconda3\lib\site-packages\gatenlp\pam\pampac.py", line 2322, in run
    fret = self.rules[idx].action(ret, context=ctx, location=location)
  File "C:\ProgramData\Anaconda3\lib\site-packages\gatenlp\pam\pampac.py", line 2489, in __call__
    return self.actions[0](succ, context=context, location=location)
  File "Main.py", line 143, in annotate_each
    for data in res.data:
AttributeError: 'Result' object has no attribute 'data'

**Comment by johann-petrak** [comment]
Could you tell which version exactly you are using (`gatenlp.__version__`)?

Is this maybe installed from the main branch and updated to a recent version of the main branch?
(if you are using a version installed from a cloned github repo, please report the commit id, e.g. 
`git rev-parse HEAD`) in addition to the version. 

If you are using a recent main branch, the 'data' attribute and parameters have been renamed to 'matches' as this name describes better and more intuitively what it is. 

The very latest update also allows to directly iterate over the matches (if any) in a result so this should work:

```python
def annotate_each(succ, context, location):
    res = succ[0]
    print(res)
    print(res.matches)
    for match in res:
    if match["name"] == "tok2":
        context.outset.add(data["span"], newtype)
```

**Comment by mdorkhah** [comment]
> Could you tell which version exactly you are using (`gatenlp.__version__`)?
> 
> Is this maybe installed from the main branch and updated to a recent version of the main branch?
> (if you are using a version installed from a cloned github repo, please report the commit id, e.g.
> `git rev-parse HEAD`) in addition to the version.
> 
> If you are using a recent main branch, the 'data' attribute and parameters have been renamed to 'matches' as this name describes better and more intuitively what it is.
> 
> The very latest update also allows to directly iterate over the matches (if any) in a result so this should work:
> 
> ```python
> def annotate_each(succ, context, location):
>     res = succ[0]
>     print(res)
>     print(res.matches)
>     for match in res:
>     if match["name"] == "tok2":
>         context.outset.add(data["span"], newtype)
> ```

Thank you, it was the version problem.
